version: "3"

services: 
  recipe_app:
    build:
      # use current folder as context
      context: .
    ports:
      - "8000:8000"
    volumes:
      # update these folders once changed:
      - ./recipe_app:/recipe_app
    # shell -runcommand "..."
    command: sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}